### PR TITLE
Godot 3.3.2 port

### PR DESCRIPTION
**Pull request by 20kdc**
Gets the game to a completable state on Godot 3.3.2.
There may be bugs that I not yet determined the existence of.
You may want to move this to another branch rather than have it on master.
Note that the Godot 3.3.2 conversion appears to cause default values to be automatically removed, which is responsible for the large amount of deletions.

### CODE REVIEW

**Comment by 20kdc** [comment]
I've confirmed game is now completable on this fork.

**Comment by huangwei4478** [comment]
can compile & run on Godot 3.3.4, so cool!

**Comment by 20kdc** [comment]
...So the fork has been up long enough that someone has forked the fork for some reason.

**Comment by 20kdc** [comment]
...so at this point it's been several Godot minor versions since anything happened with this PR.
Do I update to Godot 3.5? Do I close the PR?
Since it's been, like, nearly a year, pinging @Bauxitedev in case this was just lost.

**Comment by Bauxitedev** [comment]
Hi, sorry for ghosting you for so long. Unfortunately, due to the large health/financial impact of getting long COVID in 2020, I can no longer do any kind of open source work.

Do you want write access to the repo? So you can continue the project.

**Comment by 20kdc** [comment]
Uh... I'm not really sure what continuing the project would consist of in this case. This PR simply updates the project a bit so it will work with more modern versions of Godot 3.x. In other branches (not this PR), I tried to make it run on GLES2 for better hardware compatibility, but doing that destroys the lighting, and rebuilding it is... complex.

If it's some sort of legal obligation that prevents you from testing and then hitting the merge button yourself, then I guess you can give me write access for the interim? I doubt anything majorly breaking is going to happen to the 3.x series seeing as 4's out, so not much should need doing in the long term.

**Comment by Bauxitedev** [comment]
Like I said, it's health/financial/time reasons, not legal reasons.

Anyway, I'll go ahead and merge this, thanks.

**Pull request merged**
